### ISSUE TITLE
No ~/bin directory

### ISSUE THREAD

**Issue by mims92** [mpaluchowski/dockerized-toolbox#3]
Hello,

I ran `./toolbox.sh build` with no issue but a warning:
´SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.´

Then I ran `./toolbox.sh install` and I have errors:
```
$ ./toolbox.sh install
Installing running script for dockerized-toolbox/behat
./toolbox.sh: line 85: /c/Users/user/bin/behat: No such file or directory
Created running script ~/bin/behat
Installing running script for dockerized-toolbox/composer
        Adding run parameters:  -v ~/.ssh:/root/.ssh \
./toolbox.sh: line 85: /c/Users/user/bin/composer: No such file or directory
Created running script ~/bin/composer
Installing running script for dockerized-toolbox/pdepend
./toolbox.sh: line 85: /c/Users/user/bin/pdepend: No such file or directory
Created running script ~/bin/pdepend
Installing running script for dockerized-toolbox/phpdox
./toolbox.sh: line 85: /c/Users/user/bin/phpdox: No such file or directory
Created running script ~/bin/phpdox
Installing running script for dockerized-toolbox/phploc
./toolbox.sh: line 85: /c/Users/user/bin/phploc: No such file or directory
Created running script ~/bin/phploc
Installing running script for dockerized-toolbox/phpmd
./toolbox.sh: line 85: /c/Users/user/bin/phpmd: No such file or directory
Created running script ~/bin/phpmd
Installing running script for dockerized-toolbox/phpmetrics
./toolbox.sh: line 85: /c/Users/user/bin/phpmetrics: No such file or directory
Created running script ~/bin/phpmetrics
Installing running script for dockerized-toolbox/phpunit
./toolbox.sh: line 85: /c/Users/user/bin/phpunit: No such file or directory
Created running script ~/bin/phpunit
```

Could you help me on this please?

Running on Windows 10 with MINGW64

Thank you

**Comment by mims92** [comment]
I found a workaround on Linux:
```
1. Create folder ~/bin
2. $ mv ~bin/* /usr/bin/
3. $ chmod +x /usr/bin/ (on the entire folder or you can just execute it on the files)
4. Enjoy
```

For me it seems that it's a mistake. Or I don't know the use-case for this.

**Comment by mpaluchowski** [comment]
The "SECURITY WARNING" is normal when building containers on Windows with a Docker instance running inside a VM. If you're using Docker Toolbox you'll always see it.

As for the other error, I think that's because you don't have the `C:\Users\<you>\bin` directory. Creating it manually will fix the issue, and I'll update the script to handle the case of the directory missing.

**Comment by mims92** [comment]
Ok thank you.

You can close the issue then.
